---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pb-fpm
  name: pb-fpm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pb-fpm
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pb-fpm
    spec:
      initContainers:
        - name: init-data
          image: pb-fpm
          imagePullPolicy: IfNotPresent
          command:
            - bash
            - "-s"
            - >
              chown --changes www-data:www-data /data
          volumeMounts:
            - name: pb-data
              mountPath: /data
      containers:
        - name: pb-fpm
          image: pb-fpm
          ports:
            - name: pb-fpm
              protocol: TCP
              containerPort: 9000
          volumeMounts:
            - name: pb-data
              mountPath: /var/www/html/PrivateBin/data
            - name: fpm-config
              mountPath: /usr/local/etc/php-fpm.d
          livenessProbe:
            exec:
              command:
                - php-fpm-healthcheck
                - --listen-queue=10 # fails if there are more than 10 processes waiting in the fpm queue
                - --accepted-conn=5000 # fails after fpm has served more than 5k requests, this will force the pod to reset, use with caution
            initialDelaySeconds: 0
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - php-fpm-healthcheck # a simple ping since this means it's ready to handle traffic
            initialDelaySeconds: 1
            periodSeconds: 5
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "kill -QUIT 1; while killall -0 1; do sleep 1; done"]

      volumes:
        - name: pb-data
          persistentVolumeClaim:
            claimName: pb-data
        - name: fpm-config
          configMap:
            name: fpm-config
