---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pb-nginx
  name: pb-nginx
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: pb-nginx
