---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: privatebin
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: pb-nginx
              servicePort: http
